#!/bin/awk -f
#运行前
BEGIN {
    swtich = 0
}
#运行中
{
    if ($0 == "") {
        swtich += 1
    } else {
            gsub(/modified:/, "")
            gsub(/ /, "")
            gsub(/\t/, "")
        if ((swtich % 2 == 1) && ($0 !~ /localSync.sh|remoteSync.sh|gitawk|fastsync/)) {
            print
        }
    }

}
#运行后
# END {
#     printf "---------------------------------------------\n"
# }
